version: "3.8"

services:
  app:
    image: "node:14-slim"
    container_name: docker-nest-js
    build:
      context: .
      dockerfile: Dockerfile.slim
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - SUPPORTED_SERVICES=slack,discord
      - DISCORD_BOT_TOKEN=test
      - DISCORD_APP_ID=test
      - GITHUB_CLIENT_NAME=test
      - GITHUB_SECRETE=test
      - SLACK_APPLICATION_NAME=test
      - SLACK_APPLICATION_TOKEN=test
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - /usr/src/app/.env
    tty: true
    command: "npm start"