name: Eslint Runner

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - uses: actions/checkout@v1
        with:
          files: src/

      - name: Build
        run: |
          yarn add
          yarn run lint
